[project]
name = "eriklibs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
pycp = "eriklibs.backup_move:main"

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"
