[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[project]
name = "rememberer"
version = "0.0.1"
requires-python = ">= 3.10"
dependencies = [
  "beautifulsoup4 >= 4.12",
  "lxml >= 5",
  ]
scripts = {rememberer = "rememberer.__main__:main"}
